#!/usr/bin/Rscript

# This script expects as input:
# 1) a CSV file generated by process-working-set-data.pl.
# 2) a CSV file with columns "Value" and "App", where "Value" holds the total
#    memory footprint of the app in MB.
#
# I used these resources:
# https://stackoverflow.com/a/8365050
# https://stackoverflow.com/a/1300618
# https://discuss.analyticsvidhya.com/t/how-to-add-a-column-to-a-data-frame-in-r/3278

library(ggplot2)

args = commandArgs(trailingOnly=TRUE)
if (length(args) < 3) {
    stop("usage: ./graph-min-working-set.R working-set-csv footprint-csv output-file")
}
wsFile = args[1]
footprintFile = args[2]
outputFile = args[3]

wsData = read.csv(wsFile, header=TRUE)
wsData$Value = wsData$Value / 1048576
minWsData = subset(wsData, Type == "active_fg_read_min")

footprintData = read.csv(footprintFile, header=TRUE)
footprintData$Type = "memory_footprint"

combinedData = rbind(minWsData, footprintData)

pdf(outputFile)
ggplot(combinedData, aes(x = App)) +
    geom_col(aes(y = Value, fill = Type), position = "dodge") +
    ylab("Memory (MB)") +
    theme_classic() +
    theme(axis.title.x = element_blank()) +
    theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
    theme(axis.text = element_text(size=14), axis.title = element_text(size=16)) +
    theme(legend.title = element_blank(), legend.text = element_text(size=14)) +
    scale_fill_discrete(breaks = c("active_fg_read_min", "memory_footprint"), labels = c("Min. read WS", "Heap size")) +
    coord_fixed(0.03)
dev.off()
